#in k8_workstation cluster, below aws-auth config map will get by:
#kubectl get configmap aws-auth -n kube-system -o yaml
#copy past and add mapUsers:

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::022499022353:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-iEipbDxEoLCx
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      rolearn: arn:aws:iam::022499022353:user/suresh
      username: suresh
    - groups:
      - expense-admin
      rolearn: arn:aws:iam::022499022353:user/ramesh
      username: ramesh
  
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-10T11:43:33Z"
  name: aws-auth
  namespace: kube-system
  uid: dac101ae-b7b4-4e64-81c7-aea753b8c47b




